mod agent_service;
mod agent_settings;

use tauri::Manager;

// A-REL-002: reports whether the updater channel is actually configured.
// The checked-in endpoint uses the IANA-reserved `.invalid` domain and is
// treated as unconfigured. Release CI overlays the real HTTPS endpoint, so a
// local/dev build can never accidentally poll a placeholder update channel.
// `Config.plugins` is a JSON map (`PluginConfig(HashMap<String, JsonValue>)`),
// so the updater entry is read from `plugins.updater.endpoints`.
fn is_valid_updater_endpoint(value: &str) -> bool {
    let url = value.to_ascii_lowercase();
    url.starts_with("https://")
        && !url.contains("owner/repo")
        && !url.contains(".invalid")
        && url.ends_with("/latest.json")
}

#[tauri::command]
fn is_updater_configured(app: tauri::AppHandle) -> bool {
    let Some(updater) = app.config().plugins.0.get("updater") else {
        return false;
    };
    let Some(endpoints) = updater.get("endpoints").and_then(|value| value.as_array()) else {
        return false;
    };
    endpoints
        .iter()
        .any(|endpoint| is_valid_updater_endpoint(endpoint.as_str().unwrap_or("")))
}

#[cfg(test)]
mod updater_config_tests {
    use super::is_valid_updater_endpoint;

    #[test]
    fn checked_in_disabled_endpoint_is_not_configured() {
        assert!(!is_valid_updater_endpoint(
            "https://updates.invalid/genecode/latest.json"
        ));
    }

    #[test]
    fn placeholders_and_non_https_endpoints_are_rejected() {
        assert!(!is_valid_updater_endpoint(
            "https://github.com/OWNER/REPO/releases/latest/download/latest.json"
        ));
        assert!(!is_valid_updater_endpoint(
            "http://github.com/acme/genecode/releases/latest/download/latest.json"
        ));
        assert!(!is_valid_updater_endpoint("https://github.com/acme/genecode"));
    }

    #[test]
    fn generated_github_release_endpoint_is_accepted() {
        assert!(is_valid_updater_endpoint(
            "https://github.com/acme/genecode/releases/latest/download/latest.json"
        ));
    }
}

/// Toggle macOS window vibrancy for the "glass" theme. The desktop shows
/// through wherever the shell paints translucent surfaces; every other theme
/// paints opaque backgrounds, so clearing vibrancy fully restores them.
/// Non-macOS targets have no native equivalent wired yet (design doc §1).
#[tauri::command]
fn set_glass(window: tauri::Window, enabled: bool) {
    #[cfg(target_os = "macos")]
    {
        use window_vibrancy::{apply_vibrancy, clear_vibrancy, NSVisualEffectMaterial};
        if enabled {
            let _ = apply_vibrancy(
                &window,
                NSVisualEffectMaterial::UnderWindowBackground,
                None,
                None,
            );
        } else {
            let _ = clear_vibrancy(&window);
        }
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = (window, enabled);
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let app = tauri::Builder::default()
        .manage(agent_service::AgentServiceState::default())
        .setup(|app| {
            let app_handle = app.handle().clone();
            std::thread::spawn(move || {
                let state = app_handle.state::<agent_service::AgentServiceState>();
                if let Err(error) =
                    agent_service::ensure_agent_service(state, app_handle.clone(), None)
                {
                    eprintln!("Failed to start bundled Agent service: {error}");
                }
            });
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            agent_service::ensure_agent_service,
            agent_service::restart_agent_service,
            agent_service::get_agent_api_token,
            agent_settings::get_agent_llm_settings,
            agent_settings::save_agent_llm_settings,
            is_updater_configured,
            set_glass,
        ])
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        // A-REL-002: signed update channel (artifacts are generated by
        // `createUpdaterArtifacts` and signed with the private key configured
        // through TAURI_SIGNING_PRIVATE_KEY* in release builds).
        .plugin(tauri_plugin_updater::Builder::new().build())
        .build(tauri::generate_context!())
        .expect("error while building tauri application");

    app.run(|app_handle, event| {
        if matches!(
            event,
            tauri::RunEvent::ExitRequested { .. } | tauri::RunEvent::Exit
        ) {
            let state = app_handle.state::<agent_service::AgentServiceState>();
            state.shutdown();
        }
    });
}
