[package]
name = "genecode"
version = "0.1.0"
edition = "2024"

[lib]
name = "genecode_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-updater = "2"
keyring = "4.1.5"
getrandom = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
